global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: immich_server
    static_configs:
      - targets: ['immich-server:8081']
  
  - job_name: immich_microservices
    static_configs:
      - targets: ['immich-microservices:8081']
