#Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."luks-0669ecdc-7e02-4a81-98e4-96417c61d4a5".device = "/dev/disk/by-uuid/0669ecdc-7e02-4a81-98e4-96417c61d4a5";

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e5666443-bab3-4d95-82b0-dcae40667f95";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0cc2af36-6bf3-48df-aaa8-487a613e97de".device = "/dev/disk/by-uuid/0cc2af36-6bf3-48df-aaa8-487a613e97de";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/628C-E4F0";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/c477007e-d6b1-4d12-8206-07fcc74f4eeb"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0f4u1u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
