# NOTE: this file was generated by the Mobile NixOS installer.
{ config, lib, pkgs, ... }:

{
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/2f35078a-1513-44d9-a83e-3658eea8d6fb";
      fsType = "ext4";
    };
  };

  boot.initrd.luks.devices = {
    "LUKS-PPPN-ROOTFS" = {
      device = "/dev/disk/by-uuid/123ba5a7-4f23-4184-a398-e3232a69e37b";
    };
  };

  nix.settings.max-jobs = lib.mkDefault 3;
}
