{
  "labels": {
    "backend": "local",
    "platform": "linux/arm64"
  },
  "steps": [
    {
      "commands": [
        "nix flake show"
      ],
      "image": "bash",
      "name": "Nix flake show"
    },
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "environment": {
        "ATTIC_KEY": {
          "from_secret": "attic_key"
        }
      },
      "image": "bash",
      "name": "Setup Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.pi4b.config.system.build.toplevel' -o 'result-pi4b'"
      ],
      "image": "bash",
      "name": "Build pi4b"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-pi4b')"
      ],
      "image": "bash",
      "name": "Show pi4b info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-pi4b'"
      ],
      "image": "bash",
      "name": "Push pi4b to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.pppn.config.system.build.toplevel' -o 'result-pppn'"
      ],
      "image": "bash",
      "name": "Build pppn"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-pppn')"
      ],
      "image": "bash",
      "name": "Show pppn info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-pppn'"
      ],
      "image": "bash",
      "name": "Push pppn to Attic"
    }
  ],
  "when": [
    {
      "branch": "main",
      "event": "push"
    },
    {
      "branch": "update_flake_lock_action",
      "event": "push"
    },
    {
      "branch": "experimental",
      "event": "push"
    }
  ]
}
